
cluster.name: yl                                    # 集群名称
node.name: els-node                                 # 节点名称，仅仅是描述名称，用于在日志中区分

#path.data: /opt/elasticsearch/data                 # 数据的默认存放路径
#path.logs: /opt/elasticsearch/log                  # 日志的默认存放路径

network.bind_host: 0.0.0.0                          # 当前节点的IP地址
network.publish_host: 192.168.3.188
http.port: 9200                                     # 对外提供服务的端口，9300为集群服务的端口

#添加如下内容
#culster transport port
transport.tcp.port: 9300
transport.tcp.compress: true
cluster.initial_master_nodes: els-node1

discovery.zen.ping.unicast.hosts: ["192.168.3.200", "192.168.3.201","192.168.3.188"]
# 集群个节点IP地址，也可以使用els、els.shuaiguoxia.com等名称，需要各节点能够解析

discovery.zen.minimum_master_nodes: 2